# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

require 'google/protobuf'


descriptor_data = "\n\x12notification.proto\x12\x0cnotification\"\x89\x01\n\x13NotificationRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\ntask_title\x18\x02 \x01(\t\x12\x18\n\x10task_description\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\nuser_email\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\"8\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2p\n\x13NotificationService\x12Y\n\x10SendNotification\x12!.notification.NotificationRequest\x1a\".notification.NotificationResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Notification
  NotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.NotificationRequest").msgclass
  NotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.NotificationResponse").msgclass
end
