default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: notification_service_development

test:
  <<: *default
  database: notification_service_test

production:
  <<: *default
  database: auth_service_production
  username: <%= ENV["AUTH_SERVICE_DATABASE_USERNAME"] %>
  password: <%= ENV["AUTH_SERVICE_DATABASE_PASSWORD"] %>
  host: <%= ENV["AUTH_SERVICE_DATABASE_HOST"] %>
  port: <%= ENV["AUTH_SERVICE_DATABASE_PORT"] %>
